/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;


import config.Session;
import config.dbConnector;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import markky.loginForm;


import net.proteanit.sql.DbUtils;

/**
 *
 * @author PC11
 */
public class userDashboard extends javax.swing.JFrame {

    boolean checkAdd = true;
    public userDashboard() {
        initComponents();
        
         Image img=new ImageIcon(this.getClass().getResource("/tb.jpg")).getImage();
        this.setIconImage(img);
        
        displayData(); 
        
    }
    
    public String destination ="";
   
    public void displayData(){
        try{
            dbConnector dbc = new dbConnector();
            ResultSet rs = dbc.getData("SELECT student_no,s_name,s_program,s_section,ay_code,s_violation,s_sanction,s_type FROM violation");
            violationTable.setModel(DbUtils.resultSetToTableModel(rs));          
             rs.close();
        }catch(SQLException ex){
            System.out.println("Errors: "+ex.getMessage());     
        }

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        studentno = new javax.swing.JLabel();
        sid = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        nm = new javax.swing.JTextField();
        PROGRAM = new javax.swing.JLabel();
        SECTION = new javax.swing.JLabel();
        ST = new javax.swing.JTextField();
        aycode = new javax.swing.JLabel();
        ayc = new javax.swing.JTextField();
        violation = new javax.swing.JLabel();
        vio = new javax.swing.JComboBox<>();
        sanction = new javax.swing.JLabel();
        san = new javax.swing.JComboBox<>();
        type = new javax.swing.JLabel();
        ty = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        violationTable = new javax.swing.JTable();
        sd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PR = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        acc_name = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Add = new javax.swing.JButton();
        update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        studentno.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        studentno.setForeground(new java.awt.Color(255, 255, 255));
        studentno.setText("STUDENT NO.");
        studentno.setDoubleBuffered(true);
        jPanel4.add(studentno);
        studentno.setBounds(270, 40, 190, 29);

        sid.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jPanel4.add(sid);
        sid.setBounds(470, 40, 150, 30);

        name.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("NAME");
        name.setDoubleBuffered(true);
        jPanel4.add(name);
        name.setBounds(270, 90, 130, 29);

        nm.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jPanel4.add(nm);
        nm.setBounds(470, 90, 220, 30);

        PROGRAM.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        PROGRAM.setForeground(new java.awt.Color(255, 255, 255));
        PROGRAM.setText("PROGRAM");
        PROGRAM.setDoubleBuffered(true);
        jPanel4.add(PROGRAM);
        PROGRAM.setBounds(270, 130, 160, 50);

        SECTION.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        SECTION.setForeground(new java.awt.Color(255, 255, 255));
        SECTION.setText("SECTION");
        SECTION.setDoubleBuffered(true);
        jPanel4.add(SECTION);
        SECTION.setBounds(270, 190, 160, 40);

        ST.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        ST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STActionPerformed(evt);
            }
        });
        jPanel4.add(ST);
        ST.setBounds(470, 200, 150, 30);

        aycode.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        aycode.setForeground(new java.awt.Color(255, 255, 255));
        aycode.setText("AYCODE");
        aycode.setDoubleBuffered(true);
        jPanel4.add(aycode);
        aycode.setBounds(730, 40, 130, 29);

        ayc.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ayc.setText("2024-2025 2nd SEM");
        ayc.setEnabled(false);
        ayc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aycActionPerformed(evt);
            }
        });
        jPanel4.add(ayc);
        ayc.setBounds(910, 40, 158, 28);

        violation.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        violation.setForeground(new java.awt.Color(255, 255, 255));
        violation.setText("VIOLATION");
        violation.setDoubleBuffered(true);
        jPanel4.add(violation);
        violation.setBounds(730, 90, 160, 29);

        vio.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        vio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Threatening", "Cheating", "Alcohol", "Inappropriate touching", "Harassment", "Leaving the school premise without permission" }));
        vio.setToolTipText("");
        vio.setAutoscrolls(true);
        jPanel4.add(vio);
        vio.setBounds(910, 90, 380, 30);

        sanction.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        sanction.setForeground(new java.awt.Color(255, 255, 255));
        sanction.setText("SANCTION");
        sanction.setDoubleBuffered(true);
        jPanel4.add(sanction);
        sanction.setBounds(730, 150, 150, 29);

        san.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        san.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st WARNING", "2nd WARNING" }));
        jPanel4.add(san);
        san.setBounds(910, 150, 170, 30);

        type.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        type.setForeground(new java.awt.Color(255, 255, 255));
        type.setText("TYPE");
        type.setDoubleBuffered(true);
        jPanel4.add(type);
        type.setBounds(730, 200, 110, 30);

        ty.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        ty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minor Offense", "Major Offense" }));
        jPanel4.add(ty);
        ty.setBounds(910, 200, 170, 30);

        violationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        violationTable.setToolTipText("");
        violationTable.setDropMode(javax.swing.DropMode.ON);
        violationTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                violationTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(violationTable);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(20, 270, 1260, 280);

        sd.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        sd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sdKeyReleased(evt);
            }
        });
        jPanel4.add(sd);
        sd.setBounds(20, 70, 220, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel2.setText("Search Data");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(20, 20, 240, 37);

        PR.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        PR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BSIT", "BSHM", "BSBA", "BSCRIM" }));
        jPanel4.add(PR);
        PR.setBounds(470, 140, 150, 40);

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setBackground(new java.awt.Color(0, 255, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("DEAN");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("LOGOUT");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1172, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));

        acc_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        acc_name.setText("USER");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user.png"))); // NOI18N

        Add.setBackground(new java.awt.Color(255, 255, 255));
        Add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Add.setText("ADD");
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMouseClicked(evt);
            }
        });
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(255, 255, 255));
        update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(74, 74, 74))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(acc_name))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(Add)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel4)
                .addGap(14, 14, 14)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(acc_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 264, Short.MAX_VALUE)
                .addComponent(Add)
                .addGap(18, 18, 18)
                .addComponent(update)
                .addGap(54, 54, 54))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        loginForm lgf = new loginForm();
        JOptionPane.showMessageDialog(null,"Logged-out!");
        lgf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       Session sess = Session.getinstance();     
       
       if(sess.getUid()==0){ 
         JOptionPane.showMessageDialog(null,"NO account, Login First!");
         loginForm  lf = new loginForm();
         lf.setVisible(true);
         this.dispose();
       }else{
       acc_name.setText(""+sess.getFname()); 
       
      } 
    }//GEN-LAST:event_formWindowActivated

    private void STActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_STActionPerformed

    private void aycActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aycActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aycActionPerformed

    private void AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AddMouseClicked

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed

dbConnector dbc = new dbConnector();
String selectedsan = san.getSelectedItem().toString();
String s_sanction = selectedsan.equals("3rd WARNING") ? "contact the admin" : selectedsan;

// Check if the selected sanction is "3rd WARNING", if so, prompt to contact admin
if (selectedsan.equals("3rd WARNING")) {
    JOptionPane.showMessageDialog(null, "Please contact the admin for the 3rd WARNING.");
} else {
    if (dbc.insertData("INSERT INTO violation (student_no, s_name, s_program, s_section, ay_code, s_violation, s_sanction, s_type, u_image)"
        + " VALUES('" + sid.getText() + "','" + nm.getText() + "','" + PR.getSelectedItem() + "','" + ST.getText() + "','"
        + ayc.getText() + "','" + vio.getSelectedItem().toString() + "','" + san.getSelectedItem().toString() + "','" + ty.getSelectedItem().toString() +"','" + destination + "')")) {
        displayData();
        
        checkAdd = true;
        sid.setText("");
        nm.setText("");
        PR.setSelectedIndex(0);
        ST.setText("");
        vio.setSelectedIndex(0);
        san.setSelectedIndex(0);
        ty.setSelectedIndex(0);
    } else {
        JOptionPane.showMessageDialog(null, "Failed to add data to the database.");
    }
}


        
    }//GEN-LAST:event_AddActionPerformed

    private void violationTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_violationTableMouseClicked
        int rowlndex = violationTable.getSelectedRow();
        if(rowlndex <0){
            JOptionPane.showMessageDialog(null,"Please select an item!");
        }else{
            try{
                dbConnector dbc =  new dbConnector();
                TableModel tbl = violationTable.getModel();
                ResultSet rs = dbc.getData("SELECT * FROM violation WHERE student_no ="+tbl.getValueAt(rowlndex,0)+"");
                if(rs.next()){
                    sid.setText(""+rs.getString("student_no"));
                    nm.setText(""+rs.getString("s_name"));
                    PR.setSelectedItem(""+rs.getString("s_program"));
                    ST.setText(""+rs.getString("s_section"));             
                    vio.setSelectedItem(""+rs.getString("s_violation"));
                    san.setSelectedItem(""+rs.getString("s_sanction"));
                    ty.setSelectedItem(""+rs.getString("s_type"));               
                    Add.setEnabled(false);
                    checkAdd = false;
          
                }
            }catch(SQLException ex){
                System.out.println(""+ex);
            }
        }
    }//GEN-LAST:event_violationTableMouseClicked

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
   if(sid.getText().isEmpty()) {
    JOptionPane.showMessageDialog(null, "Please select list first");
} else {      
    if(nm.getText().isEmpty() || PR.getSelectedItem() == null || ST.getText().isEmpty()|| vio.getSelectedItem() == null || toString().isEmpty()
            || san.getSelectedItem() == null || toString().isEmpty() || ty.getSelectedItem() == null
            || toString().isEmpty()){
        JOptionPane.showMessageDialog(null, "All fields are required!");    
    
    } else {
        dbConnector dbc = new dbConnector();   
        dbc.updateData("UPDATE violation SET s_name = '"+nm.getText()+"', s_program ='"+PR.getSelectedItem()+"',"
                + " s_section ='"+ST.getText()+"', ay_code ='"+ayc.getText()+"',"
                + " s_violation ='"+vio.getSelectedItem()+"',"
                + " s_sanction ='"+san.getSelectedItem()+"', s_type ='"+ty.getSelectedItem()+"', u_image = '"+destination+"' WHERE student_no ='"+sid.getText()+"'");           
        displayData();            
        { 
            
            checkAdd = true;
            sid.setText("");
            nm.setText("");
            PR.setSelectedIndex(0);
            ST.setText("");             
            vio.setSelectedIndex(0);
            san.setSelectedIndex(0);
            ty.setSelectedIndex(0);
           
           
        }
    }
}

    }//GEN-LAST:event_updateActionPerformed

    private void sdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sdKeyReleased
        DefaultTableModel ob= (DefaultTableModel) violationTable.getModel();
        TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(ob);
        violationTable.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(sd.getText()));

    }//GEN-LAST:event_sdKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Add;
    public javax.swing.JComboBox<String> PR;
    public javax.swing.JLabel PROGRAM;
    public javax.swing.JLabel SECTION;
    public javax.swing.JTextField ST;
    private javax.swing.JLabel acc_name;
    public javax.swing.JTextField ayc;
    public javax.swing.JLabel aycode;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel name;
    public javax.swing.JTextField nm;
    public javax.swing.JComboBox<String> san;
    public javax.swing.JLabel sanction;
    private javax.swing.JTextField sd;
    public javax.swing.JTextField sid;
    public javax.swing.JLabel studentno;
    public javax.swing.JComboBox<String> ty;
    public javax.swing.JLabel type;
    public javax.swing.JButton update;
    public javax.swing.JComboBox<String> vio;
    public javax.swing.JLabel violation;
    public javax.swing.JTable violationTable;
    // End of variables declaration//GEN-END:variables
}
